### PR TITLE
allow to rename nic

### PR DESCRIPTION
**Pull request by masatake**
See the commits log.
This is needed to renamed eth0 to ensX.
I'm not sure these changes are the best way. However, they works.

### CODE REVIEW

**Comment by ssato** [comment]
It should work but I prefer to detect the NIC name in %pre w/ using ip command rather than %post.

**Comment by ssato** [comment]
Each network interface may have 'device' parameter to specify actual device name if my memory was correct.
How about using that such like followings instead?

```
  kickstart:
     ...
     dont_update_network_files: true  # Only work for RHEL 7
  ...
  guests:
     - hostname: rhua
       ip: ...
       interfaces:
          - device: ens32
             ip: ...
             ....
```

**Comment by masatake** [comment]
Yes, you are right. Renaming is not good idea and it doesn't make benefits.
I withdraw this. Thank you for reviewing.

**Comment by ssato** [comment]
BTW, it's pretty dirty hack but I introduced a new parameter "kickstart.overwrite_network_configs" to avoid overwrite ifcfg-* which NM generated if the parameter is not set to true, and I don't set it true in most cases these days.

- https://github.com/ssato/miniascape/blob/master/templates/autoinstall.d/rhel-7-min-ks.cfg#L61

**Pull request closed without merging**
